### ISSUE TITLE
the connections fail with an error 

### ISSUE THREAD

**Issue by vasanth350** [srieger1/gns3-proxy#4] opened 2021-05-11 07:50 UTC
2021-05-11 07:28:48,764 - INFO - _process:893 - client buffer is empty and maximum inactivity has reached, breaking

I am using GNS3 Web GUI and when i open a console for a device , it drop after a few secs, the error msg seen is the above. is there an option to keep alive connections. Also i notice when i try to stop/close a project it says server unreachable on the GNS3 Web GUI

My gns3_proxy_config.ini 
`backlog=10000
server-recvbuf-size=1048576
client-recvbuf-size=1048576
open-file-limit=10024
`

**Comment by srieger1** [comment] 2021-05-21 05:41
I'll try to reproduce the issue. So far we are still using the Desktop GUI client and not the Web GUI and Never experienced the issue you described. As you already stated, it seams to be related to the inactivity of the connection. Maybe I can find a keep alive option in either GNS3 or try to inject a keep alive message in gns3-proxy if the Web GUI is used together with it. Which version of GNS3 are you running? And, just to make sure (though I don't think it's the case/cause for the issue regarding you description) are there any other layer >=4 network devices between the proxy and the GNS3 Web GUI or backend?

**Comment by vasanth350** [comment] 2021-05-21 06:45
my gns3 server is hosted on a remote server - 198.18.xx.xxx
gns3 server version is 2.2.17
I have created a static IP on eth0:1 
-- `ifconfig eth0:1
eth0:1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.100  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 0c:42:a1:a9:55:2e  txqueuelen 1000  (Ethernet) `

/etc/gns3/gns3_server.conf points to the static IP - 192.168.1.100 instead of the localhost 0.0.0.0
` host = 192.168.1.100
port = 3080
`
the gns3_proxy_config.ini now points to the static IP 192.168.1.100
`hostname=0.0.0.0
port=14080
gns3-1=192.168.1.100
`
docker is run with the port mapping of 14080 to the host. 
so when i open the web gui using the address -  http://198.18.xx.xx:14080/ - it shows the gns3 projects and i am able to start the projects and console into devices.

the same config on desktop client loads the projects but cant telnet to devices .
Error - `Trying 192.168.1.100...` since i had setup a private static address for the backend gns3 server 

Am i doing the configuration wrong ? i have doubts about this but as it was working, i am not sure. 
There is no IP filtering or firewalls setup , we have VPN connection so thats the only level of firewall to connect to the remote server.

**Comment by srieger1** [comment] 2021-05-24 10:30
Thank you for providing more inside to your setup! Regarding the problem with the desktop client the only possible cause I can think of currently is, that your client running GNS3 GUI cannot reach the console ports (you can configure the console port range in GNS3 server config, per default it should use 2001-5000 TCP (see, e.g. [https://docs.gns3.com/docs/using-gns3/administration/gns3-server-configuration-file/](https://docs.gns3.com/docs/using-gns3/administration/gns3-server-configuration-file)). Problem is, that GNS3 currently does not support user-based authentication as well as encryption etc. for the console connections/websockets to the terminals. I was thinking about implementing an extension for that, but it seems to bew on the roadmap for GNS3 3.x anyway! Hence, I want to wait in which area gns3-proxy can be used as soon as GNS3 3.x is available. 

Regarding the web gui, gns3-proxy was developed before the web GUI for GNS3 was available and initially not intended to work with it but I think that we'll also drop the GNS3 GUI desktop client as soon as that will be possible regarding that all features that we need are supported in the web app. However, your right! gns3-proxy also works with the web GUI! I think, that the problem you saw is related to the same problem as described in the first paragraph! You client (the one running the web browser showing the GNS3 web GUI) currently needs to be able to reach the console ports using the IP address or supposedly hostname you specified in /etc/gns3/gns3_server.conf. Maybe using the hostname with split horizon DNS could also be an option, but for now I think the best option is to make sure, that clients can reach your IP address 192.168.1.100 and the console ports using the VPN. Then starting and using projects and nodes as well as consoles should already work, as shown in the attached screenshot. Also, I didn't experience any timeouts or breaking connections so far. Maybe you can try to analyze where on the path the state of the connection is lost? Also, as I said, it could be, that there will be changes necessary in gns3-proxy to fully support running it in front of the web GUI. However, as stated above, console connections are currently plain sockets without authentication/encryption etc. anyway in GNS3, so the VPN approach would be recommended from my side.

![gns3-proxy-and-webgui-console](https://user-images.githubusercontent.com/14318391/119334781-cc5c2900-bc8b-11eb-9d0e-12c5bf97926e.PNG)

**Comment by srieger1** [comment] 2021-06-18 23:12
fixed in #6 
Web interface is still beta however and wireshark and console connections also seam to be not 100% stable yet, even without using gns3-proxy

**Closed as completed by srieger1** 2021-06-18 23:12 UTC
